apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: pingpong-ns
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 3001
