apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20