apiVersion: v1
kind: Service
metadata:
  name: main-svc
  namespace: pingpong-ns
spec:
  type: ClusterIP
  selector:
    app: main
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
