apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-fetcher-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-fetcher
  template:
    metadata:
      labels:
        app: image-fetcher
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: image-fetcher
          image: yumol/image-fetcher:v1.3
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files