apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pingpong-ns
resources:
- pingpong/configmap.yaml
- pingpong/knative-service.yaml
- pingpong/sealedsecret.yaml
- postgres/statefulset.yaml
- persistentvolume.yaml

images:
- name: PINGPONG/IMAGE
  newName: yumol/pingpong-serverless:1.1
- name: POSTGRES/IMAGE
  newName: postgres:13.0
