apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-pwd
  namespace: pingpong-ns
spec:
  encryptedData:
    DB_PASSWORD: AgAVC+ducDchCQEaMt+NBCH+k4YxIVlOQOsQDwv2ztBFt4eMJt0T7HRtY0ClemEvsQ4I+/1OZc87+qF0jJPM/ZmA4s+YYcNwrV7upoWYpt1vVnQo2H9GxxZoUnjovnvcrHzhw5FFZd9v8ZQaXGDbewgKsXqCauz6VYXhqmIKNW3LtynlDgr2qzGTdGMdorM5m1LcsTuiBb/41kqqycy0UHyWNUS2MPqbVqzMk4LP+BrYFqIJn3XTik2pgIl6omzJGD++7M6hyRXXEji/Nn7FNCJcDUtffW5BAH+la0VXL0OwTuPTE9+Me15OzAco9kdlD7BcrV5D5IbIxZFVx7BBtEZGxCxx9fyMDxP2wveSihPONXua2DtTVXCC2TGOZQoj0tz4MAPX6tMxnDjz8NWv/oxS4H/3gfJFZEfF3T0h00suTIN8hbetPYFpU9xtvGObBgZuy6DwA5ED/8yQVt+BpG3gJIApKVdRxRpWneApedQ2FN4Mb4t9xAyPtMKuRrc6LD92HeyjuRiYI540fCAza/UONcg33dcnhVjAwHaZn8G7jZMW7+5BTGFa9vEOCyWVZLW8EnilDL5EazI8uf+HlJ4IEQLuowobokLPy0FtkjtmONeoIdf1VGOKXih5NJMzB0WWJMLgH7zsR1KjsjTkNCUS46iV+36hdfzvtf+8FawvnlEZ2lxzuXlFg19TuTG7GDE9wzA=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-pwd
      namespace: pingpong-ns

