apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-dec
  labels:
    app: random-string
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      containers:
      - name: random-string
        image: yumol/random-string:dec