apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: pingpong-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong-generator
          image: yumol/pingpong-generator:v3.1
          imagePullPolicy: Always
          ports:
          - containerPort: 2345
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: main-env
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: main-env
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: main-env
                  key: db_name