apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: yumol/main:v2.1
          imagePullPolicy: Always
        