apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project-ns
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 2345
      protocol: TCP
      targetPort: 3001
