apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: BROADCASTER/IMAGE
          imagePullPolicy: Always
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: TELEGRAM_BOT_TOKEN
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: CHAT_ID
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: project-env
                  key: nats_url
          