apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-claim
  namespace: project-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi