apiVersion: batch/v1
kind: Job
metadata:
  name: new-todo
  namespace: project-ns
spec:
  template:
    spec:
      containers:
      - name: new-todo
        image: yumol/cronjob:v1
        env:
          - name: wiki_url
            value: "https://en.wikipedia.org/wiki/Special:Random"
      restartPolicy: OnFailure