apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-rate
spec:
  metrics:
  - name: cpu-usage-rate
    initialDelay: 10m
    successCondition: result < 0.2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1617-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          sum (rate (container_cpu_usage_seconds_total{namespace="project-ns"}[10m])) / sum(machine_cpu_cores) * 100