apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-ns
#- analysistemplate.yaml
#- backend/rollout.yaml
#- backend/autoscaler.yaml
resources:
- configmap.yaml
- sealedsecret.yaml
- postgres/statefulset.yaml
- backend/service.yaml
- backend/deployment.yaml
- ingress.yaml
- frontend/service.yaml
- frontend/deployment.yaml
- broadcaster/deployment.yaml
- persistentvolumeclaim.yaml
- persistentvolume.yaml

images:
- name: BACKEND/IMAGE
  newName: yumol/backend
  newTag: 7512e7a50bb40096aa9ea5c9ca706b0b1c0cb5f1
- name: BROADCASTER/IMAGE
  newName: yumol/broadcaster
  newTag: 7512e7a50bb40096aa9ea5c9ca706b0b1c0cb5f1
- name: FRONTEND/IMAGE
  newName: yumol/frontend
  newTag: 7512e7a50bb40096aa9ea5c9ca706b0b1c0cb5f1
- name: POSTGRES/IMAGE
  newName: postgres:13.0
