apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: cpu-usage-rate
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: shared-file
          persistentVolumeClaim:
            claimName: backend-claim
      containers:
        - name: backend
          image: BACKEND/IMAGE
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /backend/healthz
               port: 3001
          livenessProbe:
            initialDelaySeconds: 20 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
               path: /backend/healthz
               port: 3001
          resources: 
            limits:
              cpu: "150m"
              memory: "100Mi"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: project-env
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: project-env
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: project-env
                  key: db_name
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files
            subPath: app-files